# Generated by Django 5.0.1 on 2024-01-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(max_length=512, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(choices=[('FOU', 'Fundacja'), ('NGO', 'Organizacja pozarządowa'), ('LC', 'Zbiórka lokalna')], default='FOU', max_length=3, verbose_name='Rodzaj instytucji'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nazwa'),
        ),
    ]
